[package]
name = "render"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
profiling = "1"
app = { path = "../app" }
color = { path = "../color" }
essential = { path = "../essential" }
ecs = { path = "../ecs" }
mesh = { path = "../mesh" }
window = { path = "../window" }
render-macros = { path = "macros" }
bitflags = "2.9.1"
encase = { version = "0.11.1", features = ["glam"] }
glam = { version = "0.30.1" }
bytemuck = { version = "1.22.0", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.26"
wgpu = { version = "24.0.1", default-features = false, features = [
    "wgsl",
    "metal",
    "naga-ir",
    "fragile-send-sync-non-atomic-wasm",
] }
wgpu-types = { version = "24", default-features = false, features = ["serde"] }
cfg-if = "1.0.0"
pollster = "0.4.0"
send_wrapper = { version = "0.6.0" }
async-trait = "0.1.50"
anyhow = "1.0.97"
winit = { version = "0.30" }
offset-allocator = { version = "0.2.0" }
derive_more = { version = "2", features = ["full"] }
asset-cook = { path = "../asset-cook" }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"

[dependencies.image]
version = "0.25.5"
default-features = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
