[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
core = { path = "../core" }
render = { path = "../render" }
egui = "0.31.1"
egui-wgpu = "0.31.1"
egui-winit = "0.31.1"
