[package]
name = "animation"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app" }
essential = { path = "../essential" }
ecs = { path = "../ecs" }
mesh = { path = "../mesh" }
asset-cook = { path = "../asset-cook" }
glam = { version = "0.30.1", features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4", "js", "serde"] }
petgraph = { version = "0.8" }
log = "0.4.27"
derive_more = { version = "2", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
async-trait = "0.1.50"
anyhow = "1.0.97"