[package]
name = "scene"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
essential = { path = "../essential" }
ecs = { path = "../ecs" }
mesh = { path = "../mesh" }
render = { path = "../render" }
asset-cook = { path = "../asset-cook" }
async-trait = "0.1.50"
anyhow = "1.0.97"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
